const DIMENSIONS = {
  COMMUNICATION_CONFLICT: 'COMMUNICATION_CONFLICT',
  TARGET_VALUE: 'TARGET_VALUE',
  TRUST_CONNECT: 'TRUST_CONNECT',
  POWER_BALANCE: 'POWER_BALANCE',
  CLOSE_NEED: 'CLOSE_NEED',
};

module.exports = {
  DIMENSIONS
};
