const { DIMENSIONS } = require('./base.js');

const PARTENER_QUESTIONS = [
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta生日是哪天？',
    type: 'text',
    options: null,
    reverse: false,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最喜欢什么花？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最擅长的菜是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最讨厌什么食物？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最讨厌的家务是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最大的爱好是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最喜欢读哪些类型的书？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'keyword_match',
      keywords: ['小说', '历史', '科幻'],
      score: 3,
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: '第一次见面时，Ta穿什么衣服？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: '吃火锅时，Ta必点的菜是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'keyword_match',
      keywords: ['毛肚', '牛肉', '虾滑'],
      score: 3,
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta在微信给你的备注是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最害怕失去什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最喜欢的影视角色是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最想去哪个城市养老？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta朋友圈背景是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最常和你说的话是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta现在面临最大的压力是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta最渴望却未曾实现的梦想是什么？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: '举例一件Ta觉得TA自己很厉害的事件。',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: 'Ta一定会被激怒的一句话是什么？（不能是脏话）',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    questionText: '你的哪个习惯Ta最不能接受？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'negative_correlation',
      matchScore: 5,
      mismatchScore: 0,
    }),
  },
  {
    dimension: 'TARGET_VALUE',
    questionText: '向Ta提出一个自己最关心的问题',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'expert_rate', maxScore: 15 }),
  },
];
module.exports = {
  PARTENER_QUESTIONS,
};
