const DIMENSIONS = {
  COMMUNICATION_CONFLICT: 'COMMUNICATION_CONFLICT',
  TARGET_VALUE: 'TARGET_VALUE',
  TRUST_CONNECT: 'TRUST_CONNECT',
  POWER_BALANCE: 'POWER_BALANCE',
  CLOSE_NEED: 'CLOSE_NEED',
};

const SELF_QUESTIONS = [
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方生日是哪天？',
    partner: '你的生日是哪天？',
    match: '双方是否准确知晓彼此生日？',
    type: 'text',
    options: null,
    reverse: false,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '你们结婚纪念日是什么时候？',
    partner: '我们的结婚纪念日是什么时候？',
    match: '双方对纪念日的记忆一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方是在哪里出生？',
    partner: '你是在哪里出生？',
    match: '出生地认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方鞋码是多少？',
    partner: '你的鞋码是多少？',
    match: '鞋码认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方的血型是什么？',
    partner: '你的血型是什么？',
    match: '血型认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢什么花？',
    partner: '你最喜欢什么花？',
    match: '花卉偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢什么运动？',
    partner: '你最喜欢什么运动？',
    match: '运动偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢吃什么？',
    partner: '你最喜欢吃什么？',
    match: '饮食偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的颜色是什么？',
    partner: '你最喜欢的颜色是什么？',
    match: '颜色偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最讨厌什么食物？',
    partner: '你最讨厌什么食物？',
    match: '厌恶食物认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的动物是什么？',
    partner: '你最喜欢的动物是什么？',
    match: '动物偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最讨厌的家务是什么？',
    partner: '你最讨厌的家务是什么？',
    match: '家务厌恶认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最擅长的菜是什么？',
    partner: '你最擅长的菜是什么？',
    match: '烹饪技能认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢哪个季节？',
    partner: '你最喜欢哪个季节？',
    match: '季节偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最大的爱好是什么？',
    partner: '你最大的爱好是什么？',
    match: '核心兴趣认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢读哪些类型的书？',
    partner: '你最喜欢读哪些类型的书？',
    match: '阅读偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'keyword_match',
      keywords: ['小说', '历史', '科幻'],
      score: 3,
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方挚友的两位名字是什么？',
    partner: '你挚友的两位名字是什么？',
    match: '社交圈认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '第一次见面时，对方穿什么衣服？',
    partner: '第一次见面时，你穿什么衣服？',
    match: '初次见面记忆一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '吃火锅时，对方必点的菜是什么？',
    partner: '你吃火锅时必点的菜是什么？',
    match: '饮食偏好默契度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'keyword_match',
      keywords: ['毛肚', '牛肉', '虾滑'],
      score: 3,
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方在微信给你的备注是什么？',
    partner: '你在微信给对方的备注是什么？',
    match: '微信备注认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最害怕失去什么？',
    partner: '你最害怕失去什么？',
    match: '恐惧点认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的睡姿是什么？',
    partner: '你最喜欢的睡姿是什么？',
    match: '私密习惯认知差异',
    options: null,
    type: 'text',
    scoreRule: JSON.stringify({ type: 'difference', max: 5, deduction: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最想去哪个城市养老？',
    partner: '你最想去哪个城市养老？',
    match: '养老规划认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方朋友圈背景是什么？',
    partner: '你的朋友圈背景是什么？',
    match: '社交展示认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最常和你说的话是什么？',
    partner: '你最常和对方说的话是什么？',
    match: '日常沟通模式认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方现在面临最大的压力是什么？',
    partner: '你现在面临最大的压力是什么？',
    match: '压力源认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最渴望却未曾实现的梦想是什么？',
    partner: '你最渴望却未曾实现的梦想是什么？',
    match: '梦想认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '举例一件对方觉得TA自己很厉害的事件。',
    partner: '举例一件你觉得你自己很厉害的事件。',
    match: '自我认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的影视角色是什么？',
    partner: '你最喜欢的影视角色是什么？',
    match: '影视偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方一定会被激怒的一句话是什么？（不能是脏话）',
    partner: '你一定会被激怒的一句话是什么？（不能是脏话）',
    match: '情绪触发点认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '你的哪个习惯对方最不能接受？',
    partner: '你最不能接受对方的哪个习惯？',
    match: '矛盾点认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'negative_correlation',
      matchScore: 5,
      mismatchScore: 0,
    }),
  },
  {
    dimension: 'TARGET_VALUE',
    self: '向对方提出一个自己最关心的问题',
    partner: '回答伴侣提出的核心问题',
    match: '关键问题共识度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'expert_rate', maxScore: 15 }),
  },
];
const PARTENER_QUESTIONS = [
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方生日是哪天？',
    partner: '你的生日是哪天？',
    match: '双方是否准确知晓彼此生日？',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '你们结婚纪念日是什么时候？',
    partner: '我们的结婚纪念日是什么时候？',
    match: '双方对纪念日的记忆一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方是在哪里出生？',
    partner: '你是在哪里出生？',
    match: '出生地认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方鞋码是多少？',
    partner: '你的鞋码是多少？',
    match: '鞋码认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方的血型是什么？',
    partner: '你的血型是什么？',
    match: '血型认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢什么花？',
    partner: '你最喜欢什么花？',
    match: '花卉偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢什么运动？',
    partner: '你最喜欢什么运动？',
    match: '运动偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢吃什么？',
    partner: '你最喜欢吃什么？',
    match: '饮食偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的颜色是什么？',
    partner: '你最喜欢的颜色是什么？',
    match: '颜色偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最讨厌什么食物？',
    partner: '你最讨厌什么食物？',
    match: '厌恶食物认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的动物是什么？',
    partner: '你最喜欢的动物是什么？',
    match: '动物偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最讨厌的家务是什么？',
    partner: '你最讨厌的家务是什么？',
    match: '家务厌恶认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最擅长的菜是什么？',
    partner: '你最擅长的菜是什么？',
    match: '烹饪技能认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢哪个季节？',
    partner: '你最喜欢哪个季节？',
    match: '季节偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最大的爱好是什么？',
    partner: '你最大的爱好是什么？',
    match: '核心兴趣认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢读哪些类型的书？',
    partner: '你最喜欢读哪些类型的书？',
    match: '阅读偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'keyword_match',
      keywords: ['小说', '历史', '科幻'],
      score: 3,
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方挚友的两位名字是什么？',
    partner: '你挚友的两位名字是什么？',
    match: '社交圈认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '第一次见面时，对方穿什么衣服？',
    partner: '第一次见面时，你穿什么衣服？',
    match: '初次见面记忆一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '吃火锅时，对方必点的菜是什么？',
    partner: '你吃火锅时必点的菜是什么？',
    match: '饮食偏好默契度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'keyword_match',
      keywords: ['毛肚', '牛肉', '虾滑'],
      score: 3,
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方在微信给你的备注是什么？',
    partner: '你在微信给对方的备注是什么？',
    match: '微信备注认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'manual_rate',
      criteria: ['完全错误', '部分正确', '完全正确'],
      score: [0, 1.5, 3],
    }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最害怕失去什么？',
    partner: '你最害怕失去什么？',
    match: '恐惧点认知一致性',
    type: 'text',
    options: null,
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的睡姿是什么？',
    partner: '你最喜欢的睡姿是什么？',
    match: '私密习惯认知差异',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'difference', max: 5, deduction: 1 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最想去哪个城市养老？',
    partner: '你最想去哪个城市养老？',
    match: '养老规划认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方朋友圈背景是什么？',
    partner: '你的朋友圈背景是什么？',
    match: '社交展示认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最常和你说的话是什么？',
    partner: '你最常和对方说的话是什么？',
    match: '日常沟通模式认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方现在面临最大的压力是什么？',
    partner: '你现在面临最大的压力是什么？',
    match: '压力源认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最渴望却未曾实现的梦想是什么？',
    partner: '你最渴望却未曾实现的梦想是什么？',
    match: '梦想认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '举例一件对方觉得TA自己很厉害的事件。',
    partner: '举例一件你觉得你自己很厉害的事件。',
    match: '自我认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方最喜欢的影视角色是什么？',
    partner: '你最喜欢的影视角色是什么？',
    match: '影视偏好认知度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '对方一定会被激怒的一句话是什么？（不能是脏话）',
    partner: '你一定会被激怒的一句话是什么？（不能是脏话）',
    match: '情绪触发点认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'exact_match', score: 5 }),
  },
  {
    dimension: DIMENSIONS.TRUST_CONNECT,
    self: '你的哪个习惯对方最不能接受？',
    partner: '你最不能接受对方的哪个习惯？',
    match: '矛盾点认知一致性',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({
      type: 'negative_correlation',
      matchScore: 5,
      mismatchScore: 0,
    }),
  },
  {
    dimension: 'TARGET_VALUE',
    self: '向对方提出一个自己最关心的问题',
    partner: '向对方提出一个自己最关心的问题',
    match: '关键问题共识度',
    type: 'text',
    options: null,
    scoreRule: JSON.stringify({ type: 'expert_rate', maxScore: 15 }),
  },
];
module.exports = {
  DIMENSIONS,
  SELF_QUESTIONS, 
  PARTENER_QUESTIONS
}
